[32m2024-07-09 12:39:33 +0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_1 - 6d1e4ee1-29a0-4f83-9b2f-b64b923fac41 - 57350 - LOGS_CAPTURED - Started capturing logs in process (pid: 57350).
[32m2024-07-09 12:39:33 +0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_1 - 6d1e4ee1-29a0-4f83-9b2f-b64b923fac41 - 57350 - taxi_trips - STEP_START - Started execution of step "taxi_trips".
[32m2024-07-09 12:39:33 +0300[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB_1 - 6d1e4ee1-29a0-4f83-9b2f-b64b923fac41 - 57350 - taxi_trips - STEP_FAILURE - Execution of step "taxi_trips" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_trips"::

duckdb.duckdb.InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: Binder Error: Referenced column "partition_date" not found in FROM clause!
Candidate bindings: "trips.payment_type"
LINE 9:         delete from trips where partition_date = '2023-03';
                                        ^

Stack Trace:
  File "/Users/abdulrahman/Documents/Dagster/venv/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/abdulrahman/Documents/Dagster/venv/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/abdulrahman/Documents/Dagster/venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/abdulrahman/Documents/Dagster/venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abdulrahman/Documents/Dagster/dagster_university/dagster_university/assets/trips.py", line 61, in taxi_trips
    conn.execute(sql_query)
[0m
