[32m2024-07-04 15:19:12 +0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b7d86bd5-c6f8-4e3a-bc45-f9470a30ff28 - 22845 - LOGS_CAPTURED - Started capturing logs in process (pid: 22845).
[32m2024-07-04 15:19:12 +0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - b7d86bd5-c6f8-4e3a-bc45-f9470a30ff28 - 22845 - taxi_trips - STEP_START - Started execution of step "taxi_trips".
[32m2024-07-04 15:19:12 +0300[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - b7d86bd5-c6f8-4e3a-bc45-f9470a30ff28 - 22845 - taxi_trips - STEP_FAILURE - Execution of step "taxi_trips" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_trips"::

duckdb.duckdb.IOException: IO Error: Could not set lock on file "/Users/abdulrahman/Documents/Dagster/dagster_university/data/staging/data.duckdb": Conflicting lock is held in /Library/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python (PID 20384) by user abdulrahman. See also https://duckdb.org/docs/connect/concurrency

Stack Trace:
  File "/Users/abdulrahman/Documents/Dagster/venv/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/abdulrahman/Documents/Dagster/venv/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 468, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/abdulrahman/Documents/Dagster/venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/abdulrahman/Documents/Dagster/venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/abdulrahman/Documents/Dagster/dagster_university/dagster_university/assets/trips.py", line 52, in taxi_trips
    conn = duckdb.connect(os.getenv("DUCKDB_DATABASE"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0m
